
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Gordon360.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Transit_Rides
{

    public System.DateTime transaction_datetime { get; set; }

    public int ride_id { get; set; }

    public string driver_username { get; set; }

    public string passenger_usernames { get; set; }

    public string request_ids { get; set; }

    public int max_capacity { get; set; }

    public string origin { get; set; }

    public string destination { get; set; }

    public System.DateTime departure_datetime { get; set; }

    public string driver_note { get; set; }

}

}
