
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Gordon360.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Transit_Requests
{

    public System.DateTime transaction_datetime { get; set; }

    public int request_id { get; set; }

    public string requester_username { get; set; }

    public Nullable<int> ride_id { get; set; }

    public string origin { get; set; }

    public string destination { get; set; }

    public System.DateTime earliest_departure_datetime { get; set; }

    public System.DateTime latest_departure_datetime { get; set; }

    public string requester_note { get; set; }

}

}
